pages:
  - id: info
    label: Info
    icon: "info"
    parameters:
      - id: versione_hmi
        name: HMI Version
        type: enum
        readonly: true
      - id: stato_rete
        name: Network Status
        type: enum
        options: [ONLINE, OFFLINE]
        readonly: true
      - id: connessione
        name: Connection
        type: enum
        options: [CAN-BUS, WIFI, ETH]
        readonly: true
      - id: uptime
        name: Uptime
        type: number
        unit: min
        precision: 0
        readonly: true
      - id: tensione_batteria
        name: Battery Volt.
        type: number
        unit: "V"
        precision: 1
        readonly: true
      - id: temperatura_cpu
        name: CPU Temp.
        type: number
        unit: "°C"
        precision: 0
        readonly: true
      - id: data_sistema
        name: Date
        type: date
        readonly: false
      - id: ora_sistema
        name: Time
        type: enum
        readonly: true
