pages:
  - id: allarmi
    label: Alarms
    icon: "alarm"
    parameters:
      - id: allarme_batteria
        name: Battery
        type: boolean
        readonly: true
      - id: allarme_temp_motore
        name: Engine Temp.
        type: boolean
        readonly: true
      - id: allarme_pressione
        name: Pressure
        type: boolean
        readonly: true
      - id: allarme_olio
        name: Engine Oil
        type: boolean
        readonly: true
      - id: allarme_abs
        name: ABS
        type: boolean
        readonly: true
      - id: allarme_airbag
        name: Airbag
        type: boolean
        readonly: true
      - id: allarme_carburante
        name: Fuel
        type: boolean
        readonly: true
      - id: livello_carburante
        name: Fuel Level
        type: percentage
        precision: 0
        readonly: true
