statusIcons:
  - id: fault
    label: Fault Status
    icon: fault
    pageId: allarmi
    parameterId: status_fault
  - id: channel
    label: Channel Status
    icon: channel
    pageId: info
    parameterId: status_channel
  - id: gps
    label: GPS Status
    icon: gps
    pageId: gps
    parameterId: status_gps
  - id: login
    label: Login Status
    icon: login
    pageId: login
    pageIdByState:
      off: login
      ok: logout
    parameterId: status_login
