statusIcons:
  - id: fault
    label: Fault Status
    icon: fault
    pageId: allarmi
    parameterId: status_fault
  - id: channel
    label: Channel Status
    icon: channel
    pageId: info
    parameterId: status_channel
  - id: gps
    label: GPS Status
    icon: gps
    pageId: gps
    parameterId: status_gps
  - id: login
    label: Login Status
    icon: login
    pageId: login
    pageIdByState:
      off: login
      ok: logout
    parameterId: status_login

headerParams:
  - id: active_waveform_name
  - id: active_preset_name
  - id: active_channel_number
  - id: crypto_algorithm
  - id: crypto_key_id
  - id: crypto_context
  - id: comm_state
  - id: comm_mode
  - id: comm_radio_silence
  - id: ora_sistema
  - id: timezone_riferimento
